language: python
python:
  - "2.7"
  
services:
    - riak

install:
    # update aptitude
    - sudo apt-get update -y
    #install debian packages
    - sudo aptitude install -y python-opencv libcurl4-openssl-dev python-dev libjpeg8-dev python-pip python-crypto python-gevent libevent-dev
    - sudo apt-get autoremove -y
    # install python requirements
    - sudo pip install thumbor --use-mirrors
    - sudo pip install pyvows --use-mirrors

script:
    # run tests
    - pyvows -c -l thumbor_riak
