language: python

services:
  - riak     # will start riak

python:
  - "2.7"
  - "2.6"
  
install:
    # update aptitude
    - sudo apt-get update -y
    #install debian packages
    - sudo apt-get install -y python-opencv libcurl4-openssl-dev python-dev libjpeg8-dev python-pip python-crypto python-gevent libevent-dev python-coverage
    - sudo apt-get autoremove -y
    # install python requirements
    - sudo pip install thumbor --use-mirrors
    - sudo pip install pyvows --use-mirrors

script:
    # run tests
    - pyvows -c -l thumbor_riak
